---
upgrade:
  - |
    Added :class:`.QubitProperties` in :class:`.Target`.
    One can access :class:`.QubitProperties` for a particular :class:`.Target` object by calling it's
    method :meth:`~.qubit_properties`.

fixes:
  - |
    Fixed an issue with :meth:`~.form_configuration` method in :class:`.Target` when attempting to get
    the :code:`Target` object, the measure instruction was missing.
    Refer to `#10168 <https://github.com/Qiskit/qiskit/issues/10168>` for more information.
